<?php

declare(strict_types=1);

/**
 * Contenu de la page publique, extrait de la maquette (Figma Make, App.tsx).
 *
 * Fichier genere : ne pas editer a la main. Il fait foi pour la page d'accueil,
 * et garantit que les 25 modules, les 11 etapes du guide et les
 * temoignages sont repris integralement, sans omission.
 */

return [
    'modules' => [
        [
            'id' => 1,
            'icon' => '🔐',
            'name' => 'Authentification',
            'tag' => 'AUTH',
            'desc' => 'JWT, RBAC, MFA TOTP, audit complet, refresh token httpOnly',
            'color' => '#5b21f5',
        ],
        [
            'id' => 2,
            'icon' => '🏫',
            'name' => 'Structure Pédagogique',
            'tag' => 'STRUCT',
            'desc' => 'Cycles, filières, niveaux, classes, salles, arborescence',
            'color' => '#00c2ff',
        ],
        [
            'id' => 3,
            'icon' => '📚',
            'name' => 'Matières & UE/EC',
            'tag' => 'SUBJECTS',
            'desc' => 'Coefficients, LMD, crédits ECTS, import Excel, assignation',
            'color' => '#c8ff00',
        ],
        [
            'id' => 4,
            'icon' => '📝',
            'name' => 'Inscriptions & Admissions',
            'tag' => 'ENROLL',
            'desc' => 'Wizard 6 étapes, matricule auto, détection doublons, transfer',
            'color' => '#ff3d8a',
        ],
        [
            'id' => 5,
            'icon' => '🧮',
            'name' => 'Notes & Moteur de Calcul',
            'tag' => 'GRADES',
            'desc' => 'Séquentiel, trimestriel, LMD, GPA, ex æquo, mentions',
            'color' => '#ffb800',
        ],
        [
            'id' => 6,
            'icon' => '📄',
            'name' => 'Bulletins & Diplômes',
            'tag' => 'BULLETIN',
            'desc' => 'PDF Puppeteer, QR Code auth, batch BullMQ, WhatsApp/email',
            'color' => '#00e5a0',
        ],
        [
            'id' => 7,
            'icon' => '💰',
            'name' => 'Gestion Financière',
            'tag' => 'FINANCE',
            'desc' => 'Orange Money, MTN MoMo, SYSCOHADA, relances auto, reçus PDF',
            'color' => '#ff4d4d',
        ],
        [
            'id' => 8,
            'icon' => '📡',
            'name' => 'Communication Multicanal',
            'tag' => 'COMM',
            'desc' => 'Email Brevo, SMS Africa\'s Talking, WhatsApp Bot, FCM Push',
            'color' => '#5b21f5',
        ],
        [
            'id' => 9,
            'icon' => '🗓️',
            'name' => 'Emplois du Temps',
            'tag' => 'TIMETABLE',
            'desc' => 'Algorithme CSP, anti-conflits, vue enseignant/salle/classe',
            'color' => '#00c2ff',
        ],
        [
            'id' => 10,
            'icon' => '✅',
            'name' => 'Présences',
            'tag' => 'ATTENDANCE',
            'desc' => 'Appel numérique, alerte parent 15 min, justificatifs upload',
            'color' => '#c8ff00',
        ],
        [
            'id' => 11,
            'icon' => '⚖️',
            'name' => 'Discipline',
            'tag' => 'DISCIPLINE',
            'desc' => 'Sanctions cascade, tableau d\'honneur, conseil de discipline',
            'color' => '#ff3d8a',
        ],
        [
            'id' => 12,
            'icon' => '🏥',
            'name' => 'Santé Scolaire',
            'tag' => 'HEALTH',
            'desc' => 'Fiche médicale, infirmerie, stock médicaments, alertes',
            'color' => '#ffb800',
        ],
        [
            'id' => 13,
            'icon' => '🎭',
            'name' => 'Vie Scolaire',
            'tag' => 'LIFE',
            'desc' => 'Clubs, événements, sport, autorisations parentales',
            'color' => '#00e5a0',
        ],
        [
            'id' => 14,
            'icon' => '📖',
            'name' => 'Bibliothèque',
            'tag' => 'LIBRARY',
            'desc' => 'Catalogue, emprunts QR, pénalités, manuels par classe',
            'color' => '#ff4d4d',
        ],
        [
            'id' => 15,
            'icon' => '🚌',
            'name' => 'Transport',
            'tag' => 'TRANSPORT',
            'desc' => 'Bus, circuits, abonnements, pointage, notification embarquement',
            'color' => '#5b21f5',
        ],
        [
            'id' => 16,
            'icon' => '🍽️',
            'name' => 'Cantine & Internat',
            'tag' => 'CATERING',
            'desc' => 'Menus, scan carte, chambres, registre nocturne, facturation',
            'color' => '#00c2ff',
        ],
        [
            'id' => 17,
            'icon' => '🏗️',
            'name' => 'Patrimoine',
            'tag' => 'ASSETS',
            'desc' => 'Inventaire code-barres, amortissements, maintenance, alertes',
            'color' => '#c8ff00',
        ],
        [
            'id' => 18,
            'icon' => '👥',
            'name' => 'RH & Paie',
            'tag' => 'HR',
            'desc' => 'IRPP, CNPS 4.2%+11.2%, FNE 1%, CFC 1.5%, DIPE, bulletins',
            'color' => '#ff3d8a',
        ],
        [
            'id' => 19,
            'icon' => '📊',
            'name' => 'Analytics & BI',
            'tag' => 'BI',
            'desc' => 'KPI temps réel, rapports, exports, prédictions',
            'color' => '#ffb800',
        ],
        [
            'id' => 20,
            'icon' => '🔔',
            'name' => 'Notifications Push',
            'tag' => 'PUSH',
            'desc' => 'FCM, WebSocket temps réel, préférences canal par utilisateur',
            'color' => '#00e5a0',
        ],
        [
            'id' => 21,
            'icon' => '🌐',
            'name' => 'Portail Parents',
            'tag' => 'PARENT',
            'desc' => 'Notes, absences, paiements, messagerie — sans installation',
            'color' => '#ff4d4d',
        ],
        [
            'id' => 22,
            'icon' => '📱',
            'name' => 'App Mobile',
            'tag' => 'MOBILE',
            'desc' => 'iOS/Android, mode hors-ligne, saisie notes tablette',
            'color' => '#5b21f5',
        ],
        [
            'id' => 23,
            'icon' => '🔒',
            'name' => 'Sécurité & Audit',
            'tag' => 'SECURITY',
            'desc' => 'Journal complet, RGPD, chiffrement AES-256, IDOR, rate limit',
            'color' => '#00c2ff',
        ],
        [
            'id' => 24,
            'icon' => '☁️',
            'name' => 'Multi-établissements',
            'tag' => 'MULTI',
            'desc' => 'Multi-tenancy Prisma, déploiement cloud, isolation données',
            'color' => '#c8ff00',
        ],
        [
            'id' => 25,
            'icon' => '🤖',
            'name' => 'IA & Prédictions',
            'tag' => 'AI',
            'desc' => 'Prédiction décrochage, recommandations pédagogiques, NLP',
            'color' => '#ff3d8a',
        ],
    ],

    'guide' => [
        [
            'step' => '00',
            'color' => '#5b21f5',
            'title' => 'Initialisation du projet',
            'icon' => '🚀',
            'subtitle' => 'Phase 0 — Monorepo Turborepo',
            'items' => [
                'Cloner le dépôt SCHOLARIS et exécuter pnpm install dans la racine du monorepo.',
                'Lancer docker-compose up -d pour démarrer PostgreSQL 16 et Redis 7.',
                'Copier .env.example vers .env et renseigner les variables (DATABASE_URL, JWT_SECRET…).',
                'Exécuter npx prisma migrate dev pour appliquer toutes les migrations.',
                'Lancer npx prisma db seed — le super-admin et les rôles système sont créés.',
                'Vérifier GET /api/health → { status: \'ok\', database: \'connected\', redis: \'connected\' }.',
                'Accéder à http://localhost:3000 → la page de connexion SCHOLARIS s\'affiche.',
            ],
            'tip' => 'Le build complet se valide avec turbo run build — zéro erreur TypeScript strict.',
            'validate' => [
                'docker-compose up -d OK',
                'prisma migrate OK',
                'seed OK',
                'health check OK',
                'login page OK',
            ],
        ],
        [
            'step' => '01',
            'color' => '#5b21f5',
            'title' => 'Authentification & Configuration',
            'icon' => '🔐',
            'subtitle' => 'Module 1 — Socle de sécurité',
            'items' => [
                'Connectez-vous avec le compte super-admin créé par le seed (admin@scholaris.cm).',
                'Allez dans Paramètres → Établissement : renseignez le nom, adresse, type et uploadez le logo.',
                'Créez les utilisateurs : Admin, Censeur, Enseignants, Secrétaire, Intendant, Parent.',
                'Définissez les rôles et permissions via Paramètres → Rôles (RBAC granulaire).',
                'Configurez le moteur de calcul : type d\'évaluation (séquentiel/trimestriel/semestriel), pondérations, seuils de mention, règle d\'arrondi.',
                'Créez l\'année académique 2025-2026 et définissez les périodes (Séq1, Séq2, Séq3… ou T1, T2, T3).',
                'Activez le MFA pour les comptes Admin et Direction (QR Code TOTP → Google Authenticator).',
            ],
            'tip' => 'Les tokens JWT expirent en 15 min (access) et 7 jours (refresh). Le journal d\'audit enregistre chaque action sensible avec l\'ancienne et la nouvelle valeur.',
            'validate' => [
                'Login JWT OK',
                'RBAC bloque accès non autorisés',
                'Audit log actif',
                'Config moteur persistée',
            ],
        ],
        [
            'step' => '02',
            'color' => '#00c2ff',
            'title' => 'Structure Pédagogique',
            'icon' => '🏫',
            'subtitle' => 'Module 2 — Squelette académique',
            'items' => [
                'Créez les cycles : Primaire, Secondaire Premier Cycle, Secondaire Second Cycle (ou L, M, D pour le supérieur).',
                'Créez les filières et les départements rattachés à chaque cycle.',
                'Créez les niveaux (6ème → Tle pour le secondaire, L1→M2 pour le supérieur) avec leur ordre d\'affichage.',
                'Créez les salles (bâtiment, étage, capacité, équipements) dans Paramètres → Salles.',
                'Créez les classes en sélectionnant : cycle → filière → niveau → enseignant principal → salle → section FR/EN.',
                'Vérifiez l\'arborescence dans la vue Tree : cycles → filières → niveaux → classes.',
            ],
            'tip' => 'La section FR/EN d\'une classe détermine la langue des bulletins générés et de l\'interface portail parent. Une classe ne peut pas excéder sa capacité maximale.',
            'validate' => [
                'Arborescence cohérente',
                'Contrôle capacité actif',
                'Lien classe-enseignant OK',
            ],
        ],
        [
            'step' => '03',
            'color' => '#c8ff00',
            'title' => 'Matières, UE et EC',
            'icon' => '📚',
            'subtitle' => 'Module 3 — Référentiel pédagogique',
            'items' => [
                'Créez les matières avec leur code unique, coefficient, heures hebdomadaires et catégorie (littéraire, scientifique, technique, langue, sport).',
                'Marquez les matières éliminatoires et définissez leur seuil minimum.',
                'Pour le supérieur LMD : créez les UE (Unités d\'Enseignement) avec leurs crédits ECTS et semestre.',
                'Créez les EC (Éléments Constitutifs) sous chaque UE avec les heures CM/TD/TP et coefficients.',
                'Vérifiez que la somme des crédits EC = crédits de l\'UE parente.',
                'Utilisez l\'import Excel pour charger en masse la grille pédagogique (template téléchargeable).',
                'Dans la matrice d\'assignation, liez chaque enseignant à ses matières et classes pour l\'année.',
            ],
            'tip' => 'Le rapport d\'import Excel liste les lignes en erreur avec la raison précise. Un enseignant peut recevoir un avertissement (non bloquant) si la matière ne correspond pas à sa spécialité déclarée.',
            'validate' => [
                'Coefficients > 0',
                'Crédits UE/EC cohérents',
                'Assignation enseignant-classe OK',
                'Import Excel OK',
            ],
        ],
        [
            'step' => '04',
            'color' => '#ff3d8a',
            'title' => 'Inscriptions & Admissions',
            'icon' => '📝',
            'subtitle' => 'Module 4 — Cycle de vie de l\'élève',
            'items' => [
                'Cliquez Nouvel élève → le wizard démarre en 6 étapes guidées.',
                'Étape 1 — Identité : nom, prénom, date et lieu de naissance, genre, nationalité, photo.',
                'Étape 2 — Parents/Tuteurs : père, mère ou tuteur légal avec numéro WhatsApp pour les notifications.',
                'Étape 3 — Scolarité antérieure : établissement précédent, moyenne, statut (nouveau/redoublant).',
                'Étape 4 — Choix pédagogiques : classe cible, régime (externe/demi-pension/internat).',
                'Étape 5 — Documents : upload acte de naissance, certificat de scolarité, photos.',
                'Étape 6 — Confirmation : le matricule est généré automatiquement (ex : LBD/2026/0142).',
                'Pour la réinscription en masse : sélectionnez la classe source → choisissez la classe de destination → confirmez.',
            ],
            'tip' => 'Le système détecte automatiquement les doublons par algorithme de similarité (nom + prénom + date de naissance). Le transfert génère un dossier numérique chiffré avec QR Code de vérification.',
            'validate' => [
                'Matricule auto unique',
                'Détection doublons OK',
                'Contrôle capacité classe OK',
                'Wizard 6 étapes OK',
            ],
        ],
        [
            'step' => '05',
            'color' => '#ffb800',
            'title' => 'Saisie des Notes & Calcul',
            'icon' => '🧮',
            'subtitle' => 'Module 5 — Cœur algorithmique',
            'items' => [
                'L\'enseignant accède à Notes → sélectionne sa classe, sa matière et la période.',
                'Il saisit les notes dans la grille (navigation clavier Tab/Entrée). Code couleur : rouge <10, orange 10-12, vert >12.',
                'Il peut marquer un élève Absent (la règle configurée s\'applique : note 0, neutralisée, ou justifiable).',
                'Il verrouille ses notes quand la saisie est complète — seul le Censeur peut déverrouiller.',
                'Le Censeur déclenche le calcul : moyennes pondérées par matière → moyenne générale → classement → mentions.',
                'Calcul séquentiel : Moy_matière = Σ(note × poids)/Σ(poids). LMD : EC → UE → semestre → GPA.',
                'Le Directeur publie les résultats — ils deviennent visibles aux parents et élèves sur le portail.',
            ],
            'tip' => 'La couverture de tests du moteur de calcul doit être > 95%. Vérifiez chaque formule avec un jeu de données connu avant la mise en production. Les ex æquo reçoivent le même rang (1,2,2,4).',
            'validate' => [
                'Calcul séquentiel exact',
                'Calcul LMD/GPA OK',
                'Ex æquo gérés',
                'Verrouillage OK',
                'Publication contrôlée',
            ],
        ],
        [
            'step' => '06',
            'color' => '#00e5a0',
            'title' => 'Bulletins & Diplômes',
            'icon' => '📄',
            'subtitle' => 'Module 6 — Documents officiels',
            'items' => [
                'Dans Bulletins → sélectionnez la classe et la période → cliquez Générer.',
                'La génération est un job BullMQ asynchrone — suivez la barre de progression en temps réel.',
                'Prévisualisez un bulletin avant envoi pour vérifier les données (notes, rang, décision du conseil).',
                'Cliquez Envoyer aux parents pour distribuer par Email (pièce jointe) et/ou WhatsApp (document).',
                'Chaque bulletin contient un QR Code unique → /verify/:code → page publique d\'authenticité.',
                'Personnalisez le template dans Paramètres → Templates : uploadez le logo, choisissez les couleurs, réorganisez les blocs.',
                'Pour les diplômes et attestations : Diplômes → sélectionnez l\'élève → choisissez le type → Générer.',
            ],
            'tip' => 'La génération batch d\'une classe de 60 élèves doit prendre moins de 2 minutes. Les PDFs sont stockés sur MinIO/S3 et livrés via URL signée. Le template HTML/CSS est personnalisable sans toucher au code.',
            'validate' => [
                'PDF généré correct',
                'QR Code auth OK',
                'Envoi WhatsApp OK',
                'Batch 60 élèves < 2 min',
            ],
        ],
        [
            'step' => '07',
            'color' => '#ff4d4d',
            'title' => 'Gestion Financière',
            'icon' => '💰',
            'subtitle' => 'Module 7 — Comptabilité SYSCOHADA',
            'items' => [
                'Configurez les types de frais par niveau et régime : inscription, scolarité, cantine, transport, internat.',
                'À l\'inscription d\'un élève, la facture est générée automatiquement avec les lignes correspondantes.',
                'Pour encaisser en espèces : Finance → Nouveau paiement → sélection élève → montant → confirmation.',
                'Pour Orange Money/MTN MoMo : initiation → le parent reçoit une demande de paiement → callback automatique.',
                'Chaque paiement génère un reçu PDF avec QR Code ET les écritures SYSCOHADA (débit/crédit) en journal.',
                'Les relances automatiques sont envoyées à J-7 (rappel), J+1 (relance), J+15, J+30 (mise en demeure).',
                'Consultez le dashboard financier : recettes du jour/mois, taux de recouvrement, impayés, trésorerie.',
            ],
            'tip' => 'La vérification HMAC du callback Mobile Money est obligatoire pour sécuriser l\'API webhook. Les remises (fratrie, bourse, social) sont déduites ligne par ligne sur la facture avec le motif.',
            'validate' => [
                'Facture auto à l\'inscription',
                'Solde mis à jour OK',
                'Écritures SYSCOHADA OK',
                'Relances auto OK',
            ],
        ],
        [
            'step' => '08',
            'color' => '#5b21f5',
            'title' => 'Communication Multicanal',
            'icon' => '📡',
            'subtitle' => 'Module 8 — Email · SMS · WhatsApp',
            'items' => [
                'Dans Communications → Envoyer : sélectionnez les destinataires (individuel, classe, niveau ou tout l\'établissement).',
                'Choisissez le canal : Email (Brevo), SMS (Africa\'s Talking) ou WhatsApp Business (Meta Cloud API).',
                'Utilisez un template prédéfini ou rédigez un message avec variables : {nom_eleve}, {classe}, {montant}, {date}.',
                'L\'envoi est toujours asynchrone via une file BullMQ — jamais en synchrone pour éviter les timeouts.',
                'En cas d\'échec : fallback automatique WhatsApp → SMS → Email selon la préférence du parent.',
                'Le chatbot WhatsApp répond automatiquement aux mots-clés : \'solde\', \'notes\', \'emploi du temps\', \'rendez-vous\'.',
                'Consultez l\'historique complet : statuts envoyé/délivré/lu/échoué avec timestamps.',
            ],
            'tip' => 'Le throttling anti-spam limite à 100 SMS/minute et 1 000 emails/heure. Configurez les préférences de canal par parent dans son profil — certains parents reçoivent uniquement sur WhatsApp.',
            'validate' => [
                'Envoi asynchrone OK',
                'Fallback canal OK',
                'Templates variables OK',
                'Historique complet',
            ],
        ],
        [
            'step' => '09-18',
            'color' => '#00c2ff',
            'title' => 'Modules 9 à 18',
            'icon' => '⚙️',
            'subtitle' => 'Modules avancés',
            'items' => [
                'Module 9 — Emplois du Temps : algorithme CSP de génération automatique, contraintes dures/souples, vues par classe/enseignant/salle, gestion des remplacements.',
                'Module 10 — Présences : appel numérique par cours (tablette/smartphone), notification parent en 15 min, justificatifs upload, statistiques.',
                'Module 11 — Discipline : sanctions (avertissement → exclusion), récompenses, conseil de discipline, impact sur le bulletin.',
                'Module 12 — Santé Scolaire : fiche médicale RBAC confidentielle, infirmerie, stock médicaments, alertes allergies.',
                'Module 13 — Vie Scolaire : clubs, événements avec calendrier, autorisations parentales, sport scolaire.',
                'Module 14 — Bibliothèque : catalogue ISBN/Dewey, emprunts/retours scan QR, pénalités, manuels par classe.',
                'Module 15 — Transport : bus, circuits, abonnements, pointage embarquement, notification parent.',
                'Module 16 — Cantine & Internat : menus, scan carte, chambres, registre nocturne, facturation.',
                'Module 17 — Patrimoine : inventaire code-barres, amortissements, maintenance, alertes assurance/contrôle.',
                'Module 18 — RH & Paie : IRPP, CNPS (4.2%+11.2%), FNE 1%, CFC 1.5%, bulletins de paie, déclarations DIPE/CNPS.',
            ],
            'tip' => 'Chaque module suit la même structure : Prisma → NestJS Service → Contrôleur → Frontend Next.js → Tests Jest + Supertest + Playwright. Aucun module n\'est considéré livré sans tests passants à > 80% de couverture.',
            'validate' => [
                'Tests Jest > 80%',
                'Tests Supertest OK',
                'Tests Playwright OK',
                'Zéro régression inter-modules',
            ],
        ],
        [
            'step' => 'F',
            'color' => '#ff3d8a',
            'title' => 'Intégration, Performance & Déploiement',
            'icon' => '🚀',
            'subtitle' => 'Phase Finale',
            'items' => [
                'Tests d\'intégration globaux : parcours complet Inscription → Notes → Bulletin → Envoi WhatsApp.',
                'Tests de charge avec k6 : 500 utilisateurs simultanés, temps de réponse < 200ms pour 95% des requêtes.',
                'Tests de sécurité : injection SQL, XSS, IDOR, rate limiting 429, JWT expiration/refresh.',
                'Dockeriser : Dockerfile multi-stage pour apps/api et apps/web.',
                'docker-compose.production.yml : PostgreSQL, Redis, MinIO, API, Web, Nginx (reverse proxy, SSL, compression).',
                'GitHub Actions CI/CD : PR → lint + tests, merge main → build Docker → deploy staging, tag release → production.',
                'Monitoring : Prometheus metrics + Grafana dashboards. Backup : pg_dump quotidien + upload S3.',
            ],
            'tip' => '« Ad augusta per angusta » — Chaque module développé. Chaque module testé. Aucune exception. — Emmanuel, TRU GROUP SARL, Juillet 2026.',
            'validate' => [
                '500 users simultanés OK',
                'Sécurité OWASP Top 10',
                'CI/CD actif',
                'Backup quotidien OK',
            ],
        ],
    ],

    'testimonials' => [
        [
            'name' => 'Dr. Marie-Thérèse Nguema',
            'role' => 'Directrice — Lycée Bilingue de Yaoundé',
            'avatar' => 'MT',
            'color' => '#5b21f5',
            'quote' => 'SCHOLARIS a transformé notre gestion. Les bulletins PDF s\'envoient automatiquement aux parents sur WhatsApp. Nos enseignants gagnent 3 heures par semaine.',
        ],
        [
            'name' => 'Prof. Emmanuel Biya',
            'role' => 'Doyen — Faculté des Sciences, Douala',
            'avatar' => 'EB',
            'color' => '#ff3d8a',
            'quote' => 'Le moteur LMD avec compensation ECTS et GPA est parfait pour notre université. La génération des relevés de notes est instantanée et irréprochable.',
        ],
        [
            'name' => 'Mme. Clarisse Ateba',
            'role' => 'Intendante — Collège Sainte-Marie',
            'avatar' => 'CA',
            'color' => '#ffb800',
            'quote' => 'Orange Money et MTN MoMo intégrés nativement ! Les parents paient depuis leur téléphone et les reçus PDF arrivent automatiquement. Zéro papier.',
        ],
    ],
];
