<?php

// Matrice RBAC portee depuis packages/prisma/src/seed.ts de la version Node.
// Fichier genere : ne pas editer a la main, il fait foi pour RbacSeeder.

return [
    'permissions' => [
        ['users', 'create', 'Créer un utilisateur'],
        ['users', 'read', 'Consulter les utilisateurs'],
        ['users', 'update', 'Modifier un utilisateur'],
        ['users', 'delete', 'Désactiver un utilisateur'],
        ['tenants', 'create', 'Créer un établissement (Super Admin)'],
        ['tenants', 'read', 'Consulter l\'établissement'],
        ['tenants', 'update', 'Modifier la configuration de l\'établissement'],
        // Retirer un établissement du parc engage des dossiers scolaires : ce
        // droit n'appartient qu'au Super Admin, jamais à l'administrateur
        // d'une école, qui pourrait sinon supprimer la sienne.
        ['tenants', 'delete', 'Retirer un établissement du parc (Super Admin)'],
        ['roles', 'create', 'Créer un rôle personnalisé'],
        ['roles', 'read', 'Consulter les rôles et leurs permissions'],
        ['roles', 'update', 'Modifier un rôle (nom, permissions)'],
        ['roles', 'delete', 'Supprimer un rôle personnalisé inutilisé'],
        ['permissions', 'read', 'Consulter la liste des permissions disponibles'],
        ['academic-years', 'create', 'Créer une année académique'],
        ['academic-years', 'read', 'Consulter les années académiques'],
        ['academic-years', 'update', 'Activer/clore une année académique'],
        ['periods', 'read', 'Consulter les périodes'],
        ['periods', 'create', 'Créer une période'],
        ['periods', 'update', 'Ouvrir/fermer/verrouiller une période de saisie'],
        ['periods', 'unlock', 'Rouvrir une période verrouillée (Admin uniquement)'],
        ['audit-logs', 'read', 'Consulter le journal d\'audit'],
        ['exams', 'create', 'Créer un examen officiel ou configurable'],
        ['exams', 'read', 'Consulter les examens, candidats et résultats'],
        ['exams', 'register', 'Inscrire/valider des candidats aux examens'],
        ['exams', 'results', 'Saisir/importer les résultats d\'examen'],
        ['reports', 'read', 'Consulter les rapports par niveau et tableaux de bord'],
        ['health', 'read', 'Consulter les dossiers médicaux (santé scolaire)'],
        ['health', 'create', 'Créer/mettre à jour un dossier médical'],
        ['cycles', 'read', 'Consulter les cycles'],
        ['cycles', 'create', 'Créer un cycle'],
        ['departments', 'read', 'Consulter les départements'],
        ['departments', 'create', 'Créer un département'],
        ['departments', 'update', 'Modifier un département'],
        ['programs', 'read', 'Consulter les filières/programmes'],
        ['programs', 'create', 'Créer une filière/un programme'],
        ['programs', 'update', 'Modifier une filière/un programme'],
        ['levels', 'read', 'Consulter les niveaux'],
        ['levels', 'create', 'Créer un niveau'],
        ['levels', 'update', 'Modifier un niveau'],
        ['levels', 'delete', 'Supprimer un niveau'],
        ['classrooms', 'read', 'Consulter les classes'],
        ['classrooms', 'create', 'Créer une classe'],
        ['classrooms', 'update', 'Modifier une classe'],
        ['rooms', 'read', 'Consulter les salles'],
        ['rooms', 'create', 'Créer une salle'],
        ['rooms', 'update', 'Modifier une salle'],
        ['structure', 'read', 'Consulter l\'arborescence académique complète'],
        ['communication-templates', 'create', 'Créer un modèle de communication'],
        ['communication-templates', 'read', 'Consulter les modèles de communication'],
        ['communication-templates', 'update', 'Modifier un modèle de communication'],
        ['communications', 'create', 'Envoyer une communication'],
        ['communications', 'read', 'Consulter le journal des communications'],
        ['internal-messages', 'create', 'Envoyer un message interne'],
        ['internal-messages', 'read', 'Consulter la messagerie interne'],
        ['subjects', 'read', 'Consulter les matières'],
        ['subjects', 'create', 'Créer une matière (ou importer depuis Excel)'],
        ['subjects', 'update', 'Modifier une matière'],
        ['subjects', 'delete', 'Supprimer une matière'],
        ['teaching-units', 'read', 'Consulter les unités d\'enseignement (UE)'],
        ['teaching-units', 'create', 'Créer une unité d\'enseignement (UE)'],
        ['course-elements', 'read', 'Consulter les éléments constitutifs (EC)'],
        ['course-elements', 'create', 'Créer un élément constitutif (EC)'],
        ['subject-assignments', 'read', 'Consulter les assignations enseignant/matière'],
        ['subject-assignments', 'create', 'Assigner un enseignant à une matière ou un EC'],
        ['students', 'create', 'Créer un élève (dossier + parents)'],
        ['students', 'read', 'Consulter les élèves'],
        ['students', 'update', 'Modifier un dossier élève'],
        ['students', 'import', 'Importer des élèves depuis Excel'],
        ['enrollments', 'create', 'Inscrire un élève dans une classe'],
        ['enrollments', 'read', 'Consulter les inscriptions'],
        ['enrollments', 'update', 'Annuler/suspendre une inscription'],
        ['enrollments', 're-enroll', 'Réinscription en lot d\'une classe vers une autre'],
        ['admissions', 'create', 'Enregistrer une candidature d\'admission'],
        ['admissions', 'read', 'Consulter les candidatures d\'admission'],
        ['admissions', 'decide', 'Accepter/refuser/mettre en liste d\'attente une candidature'],
        ['fee-structures', 'create', 'Créer une grille tarifaire'],
        ['fee-structures', 'read', 'Consulter les grilles tarifaires'],
        ['invoices', 'create', 'Générer une ou plusieurs factures élève'],
        ['invoices', 'read', 'Consulter les factures'],
        ['payments', 'create', 'Enregistrer un paiement'],
        ['payments', 'read', 'Consulter un paiement / reçu'],
        ['discounts', 'create', 'Appliquer une réduction/bourse à une facture'],
        ['finance-dashboard', 'read', 'Consulter les indicateurs financiers de l\'établissement'],
        ['grades', 'create', 'Saisir des notes (individuelle ou collective)'],
        ['grades', 'read', 'Consulter les notes et résultats'],
        ['grades', 'update', 'Modifier une note avant verrouillage'],
        ['grades', 'import', 'Importer des notes depuis Excel'],
        ['grades', 'lock', 'Verrouiller la saisie d\'une évaluation'],
        ['grades', 'unlock', 'Rouvrir une saisie verrouillée (censeur/admin)'],
        ['grades', 'calculate', 'Calculer moyennes et classements (période ou bilan annuel)'],
        ['grades', 'progress', 'Consulter l\'avancement de la saisie des notes'],
        ['grades', 'deliberation', 'Délibérer (décisions, observations) sur une période'],
        ['grades', 'publish', 'Publier les résultats aux parents/élèves'],
        ['bulletins', 'generate', 'Générer les bulletins d\'une classe/période'],
        ['bulletins', 'read', 'Consulter/télécharger un bulletin'],
        ['bulletins', 'send', 'Envoyer les bulletins aux parents/élèves'],
        ['timetables', 'read', 'Consulter les emplois du temps'],
        ['timetables', 'create', 'Créer un créneau d\'emploi du temps'],
        ['timetables', 'update', 'Modifier un créneau d\'emploi du temps'],
        ['timetables', 'delete', 'Supprimer un créneau d\'emploi du temps'],
        ['attendance', 'read', 'Consulter les présences/absences'],
        ['attendance', 'create', 'Faire l\'appel / saisir une absence'],
        ['attendance', 'update', 'Modifier une présence saisie'],
        ['discipline', 'read', 'Consulter les incidents disciplinaires'],
        ['discipline', 'create', 'Déclarer un incident disciplinaire'],
        ['discipline', 'update', 'Modifier ou cloturer un incident disciplinaire'],
        ['course-log', 'read', 'Consulter le cahier de textes'],
        ['course-log', 'create', 'Créer une séance de cahier de textes'],
        ['course-log', 'update', 'Modifier une séance de cahier de textes'],
        ['course-log', 'read-all', 'Consulter le cahier de textes de tout l\'établissement'],
        ['school-life', 'read', 'Consulter les clubs et activités scolaires'],
        ['school-life', 'create', 'Créer un club/une activité scolaire'],
        ['library', 'read', 'Consulter le catalogue et les emprunts'],
        ['library', 'create', 'Enregistrer un ouvrage ou un emprunt'],
        ['library', 'update', 'Modifier/retourner un emprunt'],
        ['transport', 'read', 'Consulter les circuits et abonnements transport'],
        ['transport', 'create', 'Créer un circuit ou un abonnement transport'],
        ['transport', 'update', 'Modifier un circuit ou un abonnement transport'],
        ['catering', 'read', 'Consulter les menus et abonnements cantine'],
        ['catering', 'create', 'Créer un menu ou un abonnement cantine'],
        ['catering', 'update', 'Modifier un menu ou un abonnement cantine'],
        ['assets', 'read', 'Consulter le patrimoine (biens, équipements)'],
        ['assets', 'create', 'Enregistrer un bien au patrimoine'],
        ['assets', 'update', 'Modifier un bien du patrimoine'],
        ['assets', 'delete', 'Retirer un bien du patrimoine'],
        ['hr', 'read', 'Consulter les dossiers employés et congés'],
        ['hr', 'create', 'Créer un employé ou une demande de congé'],
        ['hr', 'update', 'Modifier un dossier employé ou statut de congé'],
        ['users', 'assign-roles', 'Assigner un ou plusieurs rôles à un utilisateur'],
        ['payments', 'cashout', 'Initier un décaissement / paiement via CAMOO'],
    ],

    'roles' => [
        [
            // Délégué régional ou départemental. Ses permissions sont celles
            // d'une consultation de pilotage ; ce qui le distingue du Super
            // Admin n'est pas ce qu'il peut faire, mais l'étendue sur laquelle
            // il le fait — portée par le périmètre du compte, pas par le rôle.
            'name' => 'Délégué',
            'description' => 'Pilotage des établissements de son périmètre — lecture et rapports',
            'permissions' => [
                'tenants:read',
                'students:read',
                'grades:read',
                'bulletins:read',
                'finance-dashboard:read',
                'attendance:read',
                'exams:read',
                'audit-logs:read',
            ],
        ],
        [
            // Auditeur : lecture stricte, aucune écriture nulle part. Le rôle
            // existe pour qu'un contrôle externe puisse être ouvert sans
            // accorder au passage le moindre droit de modification.
            'name' => 'Observateur',
            'description' => 'Consultation seule, sans aucun droit d\'écriture',
            'permissions' => [
                'tenants:read',
                'students:read',
                'classrooms:read',
                'enrollments:read',
                'grades:read',
                'bulletins:read',
                'attendance:read',
                'exams:read',
                'finance-dashboard:read',
                'invoices:read',
                'audit-logs:read',
            ],
        ],
        [
            // Administrateur d'une tutelle ministérielle. Son périmètre
            // traverse toutes les régions mais ne couvre qu'une partie des
            // établissements de chacune : il ne se déduit pas de la géographie.
            'name' => 'Admin Ministère',
            'description' => 'Pilotage des établissements relevant de sa tutelle',
            'permissions' => [
                'tenants:read',
                'tenants:create',
                'tenants:update',
                'students:read',
                'grades:read',
                'bulletins:read',
                'attendance:read',
                'exams:read',
                'finance-dashboard:read',
                'hr:read',
                'audit-logs:read',
            ],
        ],
        [
            // Professeur principal : un enseignant qui voit toute sa classe.
            // La différence n'est pas dans ce qu'il saisit — il saisit ses
            // notes comme les autres — mais dans ce qu'il consulte, pour
            // préparer le conseil de classe.
            'name' => 'Professeur principal',
            'description' => 'Enseignant responsable d\'une classe — suivi global et conseil de classe',
            'permissions' => [
                'students:read',
                'grades:create',
                'grades:read',
                'attendance:create',
                'attendance:read',
                'discipline:read',
                'bulletins:read',
                'course-log:create',
                'course-log:read',
                'course-log:update',
                'timetables:read',
                'internal-messages:read',
                'internal-messages:create',
            ],
        ],
        [
            'name' => 'Responsable RH',
            'description' => 'Personnel, contrats, carrières, congés',
            'permissions' => [
                // Les congés relèvent des permissions RH : « hr:read »
                // couvre déjà « dossiers employés et congés ». Un jeu de
                // permissions séparé donnerait deux vérités sur le même droit.
                'hr:read', 'hr:create', 'hr:update',
                'internal-messages:read', 'internal-messages:create',
            ],
        ],
        [
            'name' => 'Responsable cantine',
            'description' => 'Menus, abonnements et repas servis',
            'permissions' => [
                'catering:read', 'catering:create', 'catering:update',
                'students:read',
                'internal-messages:read', 'internal-messages:create',
            ],
        ],
        [
            'name' => 'Responsable transport',
            'description' => 'Véhicules, itinéraires et élèves transportés',
            'permissions' => [
                'transport:read', 'transport:create', 'transport:update',
                'students:read',
                'internal-messages:read', 'internal-messages:create',
            ],
        ],
        [
            'name' => 'Responsable maintenance',
            'description' => 'Patrimoine, équipements et interventions',
            'permissions' => [
                'assets:read', 'assets:create', 'assets:update',
                'rooms:read',
                'internal-messages:read', 'internal-messages:create',
            ],
        ],
        [
            'name' => 'Responsable discipline',
            'description' => 'Incidents, sanctions et convocations',
            'permissions' => [
                'discipline:read', 'discipline:create', 'discipline:update',
                'attendance:read',
                'students:read',
                'internal-messages:read', 'internal-messages:create',
            ],
        ],
        [
            // Responsable légal secondaire : il suit la scolarité mais
            // n'engage pas les paiements. Le responsable financier, lui, voit
            // la facture et la règle. Confondre les deux ferait recevoir les
            // relances de scolarité à qui n'a pas à les payer.
            'name' => 'Responsable secondaire',
            'description' => 'Second responsable d\'un élève — suivi scolaire sans accès financier',
            'permissions' => [
                'students:read',
                'grades:read',
                'bulletins:read',
                'attendance:read',
                'internal-messages:read',
                'internal-messages:create',
            ],
        ],
        [
            'name' => 'Admin Établissement',
            'description' => 'Administrateur technique de l\'établissement — config, moteur de calcul, utilisateurs',
            'permissions' => [
                'tenants:read',
                'tenants:update',
                'users:create',
                'users:read',
                'users:update',
                'users:delete',
                'users:assign-roles',
                'academic-years:create',
                'academic-years:read',
                'academic-years:update',
                'periods:read',
                'periods:create',
                'periods:update',
                'periods:unlock',
                'audit-logs:read',
                'cycles:read',
                'cycles:create',
                'departments:read',
                'departments:create',
                'departments:update',
                'programs:read',
                'programs:create',
                'programs:update',
                'levels:read',
                'levels:create',
                'levels:update',
                'levels:delete',
                'classrooms:read',
                'classrooms:create',
                'classrooms:update',
                'rooms:read',
                'rooms:create',
                'rooms:update',
                'structure:read',
                'subjects:read',
                'subjects:create',
                'subjects:update',
                'subjects:delete',
                'teaching-units:read',
                'teaching-units:create',
                'course-elements:read',
                'course-elements:create',
                'subject-assignments:read',
                'subject-assignments:create',
                'students:create',
                'students:read',
                'students:update',
                'students:import',
                'enrollments:create',
                'enrollments:read',
                'enrollments:update',
                'enrollments:re-enroll',
                'admissions:create',
                'admissions:read',
                'grades:read',
                'grades:unlock',
                'grades:calculate',
                'grades:import',
                'grades:progress',
                'bulletins:generate',
                'bulletins:read',
                'bulletins:send',
                'fee-structures:create',
                'fee-structures:read',
                'invoices:create',
                'invoices:read',
                'finance-dashboard:read',
                'timetables:read',
                'timetables:create',
                'timetables:update',
                'timetables:delete',
                'attendance:read',
                'discipline:read',
                'school-life:read',
                'school-life:create',
                'library:read',
                'transport:read',
                'transport:create',
                'catering:read',
                'catering:create',
                'hr:read',
                'hr:create',
                'hr:update',
                'assets:read',
                'assets:create',
                'assets:update',
                'assets:delete',
                'communications:read',
                'communication-templates:create',
                'communication-templates:read',
                'communication-templates:update',
                'internal-messages:read',
                'internal-messages:create',
                'exams:create',
                'exams:read',
                'exams:register',
                'exams:results',
                'reports:read',
                'payments:cashout',
            ],
        ],
        [
            'name' => 'Directeur',
            'description' => 'Directeur de l\'établissement — vision globale, décisions stratégiques',
            'permissions' => [
                'tenants:read',
                'users:read',
                'academic-years:read',
                'periods:read',
                'cycles:read',
                'departments:read',
                'programs:read',
                'levels:read',
                'classrooms:read',
                'rooms:read',
                'structure:read',
                'subjects:read',
                'teaching-units:read',
                'course-elements:read',
                'subject-assignments:read',
                'students:read',
                'enrollments:read',
                'admissions:read',
                'grades:read',
                'grades:progress',
                'fee-structures:read',
                'invoices:read',
                'payments:read',
                'finance-dashboard:read',
                'communications:read',
                'communication-templates:read',
                'internal-messages:read',
                'internal-messages:create',
                'audit-logs:read',
                'bulletins:read',
                'timetables:read',
                'attendance:read',
                'discipline:read',
                'course-log:read',
                'course-log:read-all',
                'school-life:read',
                'library:read',
                'transport:read',
                'catering:read',
                'assets:read',
                'hr:read',
                'admissions:decide',
                'grades:publish',
                'discipline:create',
                'users:create',
                'users:update',
                'users:assign-roles',
                'academic-years:create',
                'academic-years:update',
                'periods:create',
                'periods:update',
                'bulletins:generate',
                'bulletins:send',
                'exams:create',
                'exams:read',
                'exams:results',
                'reports:read',
            ],
        ],
        [
            'name' => 'Censeur',
            'description' => 'Censeur — responsable pédagogique (calcul, délibération, vie scolaire)',
            'permissions' => [
                'cycles:read',
                'departments:read',
                'programs:read',
                'levels:read',
                'classrooms:read',
                'classrooms:create',
                'classrooms:update',
                'rooms:read',
                'structure:read',
                'subjects:read',
                'subject-assignments:read',
                'subject-assignments:create',
                'students:read',
                'enrollments:read',
                'enrollments:update',
                'academic-years:read',
                'periods:read',
                'periods:create',
                'periods:update',
                'timetables:read',
                'timetables:create',
                'timetables:update',
                'timetables:delete',
                'grades:read',
                'grades:unlock',
                'grades:calculate',
                'grades:progress',
                'grades:deliberation',
                'bulletins:generate',
                'bulletins:read',
                'attendance:read',
                'attendance:create',
                'attendance:update',
                'discipline:read',
                'discipline:create',
                'course-log:read',
                'course-log:read-all',
                'school-life:read',
                'school-life:create',
                'catering:read',
                'catering:create',
                'internal-messages:read',
                'internal-messages:create',
            ],
        ],
        [
            'name' => 'Chef de département',
            'description' => 'Coordination pédagogique d\'un département/filière (matières, classes, emplois du temps)',
            'permissions' => [
                'cycles:read',
                'departments:read',
                'programs:read',
                'levels:read',
                'structure:read',
                'academic-years:read',
                'periods:read',
                'subjects:read',
                'subjects:create',
                'subjects:update',
                'teaching-units:read',
                'teaching-units:create',
                'course-elements:read',
                'course-elements:create',
                'subject-assignments:read',
                'subject-assignments:create',
                'classrooms:read',
                'classrooms:create',
                'classrooms:update',
                'rooms:read',
                'students:read',
                'enrollments:read',
                'timetables:read',
                'timetables:create',
                'timetables:update',
                'timetables:delete',
                'attendance:read',
                'attendance:create',
                'discipline:read',
                'discipline:create',
                'school-life:read',
                'school-life:create',
                'internal-messages:read',
                'internal-messages:create',
            ],
        ],
        [
            'name' => 'Surveillant général',
            'description' => 'Vie scolaire — présences, retards, sorties, discipline (hors calcul pédagogique)',
            'permissions' => [
                'classrooms:read',
                'students:read',
                'enrollments:read',
                'academic-years:read',
                'periods:read',
                'timetables:read',
                'attendance:read',
                'attendance:create',
                'attendance:update',
                'discipline:read',
                'discipline:create',
                'course-log:read',
                'course-log:read-all',
                'school-life:read',
                'school-life:create',
                'internal-messages:read',
                'internal-messages:create',
            ],
        ],
        [
            'name' => 'Enseignant',
            'description' => 'Enseignant — saisie notes/présences, consultation de sa classe',
            'permissions' => [
                'classrooms:read',
                'students:read',
                'enrollments:read',
                'subjects:read',
                'subject-assignments:read',
                'academic-years:read',
                'periods:read',
                'timetables:read',
                'grades:create',
                'grades:read',
                'grades:update',
                'grades:lock',
                'grades:import',
                'grades:progress',
                'attendance:create',
                'attendance:read',
                'discipline:create',
                'course-log:read',
                'course-log:create',
                'course-log:update',
                'internal-messages:read',
                'internal-messages:create',
            ],
        ],
        [
            'name' => 'Intendant',
            'description' => 'Intendant — finance, patrimoine, transport, cantine, paie',
            'permissions' => [
                'fee-structures:create',
                'fee-structures:read',
                'invoices:create',
                'invoices:read',
                'payments:create',
                'payments:read',
                'discounts:create',
                'finance-dashboard:read',
                'assets:read',
                'assets:create',
                'assets:update',
                'assets:delete',
                'transport:read',
                'transport:create',
                'catering:read',
                'catering:create',
                'hr:read',
                'hr:create',
                'hr:update',
                'students:read',
                'enrollments:read',
                'classrooms:read',
                'internal-messages:read',
                'internal-messages:create',
                'payments:cashout',
            ],
        ],
        [
            'name' => 'Comptable',
            'description' => 'Comptable — facturation, encaissements, tableau de bord finance (sans patrimoine ni paie)',
            'permissions' => [
                'fee-structures:read',
                'invoices:create',
                'invoices:read',
                'payments:create',
                'payments:read',
                'discounts:create',
                'finance-dashboard:read',
                'students:read',
                'enrollments:read',
                'classrooms:read',
                'internal-messages:read',
                'internal-messages:create',
            ],
        ],
        [
            'name' => 'Secrétaire',
            'description' => 'Secrétaire — inscriptions, admissions, communication, bibliothèque, transport/cantine',
            'permissions' => [
                'students:create',
                'students:read',
                'students:update',
                'students:import',
                'enrollments:create',
                'enrollments:read',
                'enrollments:update',
                'admissions:create',
                'admissions:read',
                'cycles:read',
                'departments:read',
                'programs:read',
                'levels:read',
                'classrooms:read',
                'rooms:read',
                'structure:read',
                'academic-years:read',
                'subjects:read',
                'communications:create',
                'communications:read',
                'communication-templates:read',
                'bulletins:generate',
                'bulletins:read',
                'bulletins:send',
                'library:read',
                'library:create',
                'transport:read',
                'transport:create',
                'catering:read',
                'catering:create',
                'internal-messages:read',
                'internal-messages:create',
                'exams:read',
                'exams:register',
            ],
        ],
        [
            'name' => 'Infirmier(ère)',
            'description' => 'Santé scolaire — dossiers médicaux, allergies, vaccinations, suivi sanitaire',
            'permissions' => [
                'health:read',
                'health:create',
                'students:read',
                'internal-messages:read',
                'internal-messages:create',
            ],
        ],
        [
            'name' => 'Bibliothécaire',
            'description' => 'Bibliothèque — catalogue, emprunts, retours',
            'permissions' => [
                'library:read',
                'library:create',
                'library:update',
                'students:read',
                'internal-messages:read',
                'internal-messages:create',
            ],
        ],
        [
            'name' => 'Parent',
            'description' => 'Parent d\'élève — consultation scopée à ses propres enfants',
            'permissions' => [
                'grades:read',
                'students:read',
                'communications:read',
                'internal-messages:read',
                'internal-messages:create',
            ],
        ],
        [
            'name' => 'Élève',
            'description' => 'Élève — consultation scopée à ses propres données',
            'permissions' => [
                'grades:read',
                'students:read',
                'internal-messages:read',
            ],
        ],
    ],
];
